name: 'Scanner Action'
description: ''
inputs:
  token:
    description: "GitHub Token"
    required: true
  external_repository_token:
    description: "External Repository GitHub Token"
    required: false
  scanner:
    description: "Type of scanner"
    required: true
runs:
  using: 'node20'
  main: 'index.js'