name: 'Scanner Action'
description: ''
inputs:
  token:
    description: "GitHub Token"
    required: true
  external-repository-token:
    description: "External Repository GitHub Token"
    required: false
  scanner:
    description: "Type of scanner"
    required: true
outputs:
  notification_severity_filter:
    description: "Severity filter for fetching alerts"
  notification_severity_threshold:
    description: "Severity threshold for alert to be triggered"
  notification_slack_channel_id:
    description: 'Slack channel id for notifications'
  notification_slack_enabled:
    description: 'Enable Slack notifications'
  notification_pull_request_enabled:
    description: 'Enable pull request notifications'
runs:
  using: 'node20'
  main: 'dist/index.js'