name: 'Scanner Action'
description: ''
inputs:
  token:
    description: "GitHub Token"
    required: true
  external-repository-token:
    description: "External Repository GitHub Token"
    required: false
  scanner:
    description: "Type of scanner"
    required: true
  command:
    description: "Comma seperated list of commands. Available commands are: allowlist, notifications"
    required: true
outputs:
  notification_severity_alert_found:
    description: "Alert with specified threshold severity has been found"
  notification_severity_overview:
    description: "Overview of amount of alerts with severity found"
  notification_severity_filter:
    description: "Severity filter for fetching alerts"
  notification_severity_threshold:
    description: "Alerts with threshold matching severity triggers notifications"
  notification_slack_channel_id:
    description: 'Slack channel id for notifications'
  notification_slack_enabled:
    description: 'Enabled Slack notifications'
  notification_slack_block:
    description: 'Notification in Slack Block format'
  notification_pull_request_enabled:
    description: 'Enabled pull request notifications'
  notification_markdown:
    description: 'Notification in markdown format'
runs:
  using: 'node20'
  main: 'dist/index.js'