version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - "/"
      - "/.github/actions/*"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Europe/Oslo"
      day: "monday"
    cooldown:
      default-days: 4
    groups:
      codeql-actions:
        applies-to: version-updates
        patterns:
        - "github/codeql-action/*"
      minor-and-patch:
        applies-to: version-updates
        update-types:
        - "minor"
        - "patch"
      major-updates:
        applies-to: version-updates
        update-types:
        - "major"
  - package-ecosystem: "npm"
    directory: "/scanner-action"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Europe/Oslo"
      day: "monday"
    cooldown:
      default-days: 7
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
        - "minor"
        - "patch"
      major-updates:
        applies-to: version-updates
        update-types:
        - "major"