name: 'Entur/Security/Code Scanning'

on:
    workflow_call:
        
jobs:
    get-repository-languages:
        runs-on: ubuntu-latest
        outputs: 
            repository_languages: ${{ env.GHA_SECURITY_CODE-SCANNING_REPOSITORY_LANGUAGES }} 
        steps:
            - id: get-repository-languages
              run: |
                  #TODO: maybe at some point it will be possible to ask `gh codeql` for a list of supported languages6
                  languages="$(gh api /repos/${{ github.repository }}/languages | \
                    jq 'keys 
                        | .[] as $langs
                        | {
                            "C":"c-cpp",
                            "C++":"c-cpp",
                            "C#":"csharp",
                            "Go":"go",
                            "Java":"java-kotlin",
                            "JavaScript":"javascript-typescript",
                            "TypeScript":"javascript-typescript",
                            "Kotlin":"java-kotlin",
                            "Python":"python",
                            "Ruby":"ruby",
                            "Swift":"swift"
                          } as $supported 
                        | $langs         # operate on all the languages
                        | $supported[.]  # and lookup their values, null if not found
                        | select(.)      # select removes null values
                    ' | \
                    jq --slurp --compact-output 'unique')" # make a oneliner, and remove duplicates
            
                  echo 'GHA_SECURITY_CODE-SCANNING_REPOSITORY_LANGUAGES='$languages >> $GITHUB_ENV
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    codeql-analysis:
        runs-on: ubuntu-latest
        needs: get-repository-languages
        permissions:
            # required for all workflows
            security-events: write
            # only required for workflows in private repositories
            actions: read
            contents: read

            issues: write # required for creating issues, and/or adding issue comments
            pull-requests: write # required for creating comments on pull requests
        strategy:
            fail-fast: false
            matrix:
                language: ${{fromJson(needs.get-repository-languages.outputs.repository_languages)}}
        steps:
            - name: "Checkout repository"
              uses: actions/checkout@v4
            - name: "Initialize CodeQL for Java"
              uses: github/codeql-action/init@v3
              with:
                languages: ${{ matrix.language }}
                build-mode: none
              if: matrix.language == 'java-kotlin'
            - name: "Initialize CodeQL"
              uses: github/codeql-action/init@v3
              with:
                languages: ${{ matrix.language }}
              if: matrix.language != 'java-kotlin'
            - name: "Perform CodeQL Analysis"
              id: codeql-analysis
              uses: github/codeql-action/analyze@v3
              with:
                category: "/language:${{ matrix.language }}"
            - name: "Check for critical vulnerabilities"
              id: check-for-critical-vulnerabilities
              run: |
                alerts="$(gh api \
                --method GET \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                /repos/${{ github.repository }}/code-scanning/alerts \
                -F severity="critical" -F state="open" -F ref="${{ github.ref }}")"
                if [ "$alerts" == "[]" ]; then
                  exit 0
                else
                  exit 1
                fi
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: "Create comment on pull request if critical vulnerabilities found"
              if: failure()
              run: |
                gh api /repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
                  -H "Accept: application/vnd.github.v3+json" \
                  -- field "body=:no_entry: :no_entry: :no_entry: :no_entry: :no_entry: :no_entry: :no_entry: :no_entry: :no_entry: :no_entry: :no_entry: :no_entry: :no_entry: :no_entry: \
                  Code scanning detected critical vulnerabilities in the code. In order to merge, please address these issues first. \
                  The scan results can be found [here](https://github.com/${{ github.repository }}/security/code-scanning?query=is%3Aopen+pr%3A${{ github.event.pull_request.number }}). \
                  If you believe one or more of the reported vulnerabilities are false positives/cannot be fixed/can be ignored, please see the [Code Scanning documentation](https://github.com/entur/gha-security/blob/code-scanning-ruleset/README-code_scanning.md#white-listing-vulnerabilities) on how to whitelist. \
                  :no_entry: :no_entry: :no_entry: :no_entry: :no_entry: :no_entry: :no_entry: :no_entry: :no_entry: :no_entry: :no_entry: :no_entry: :no_entry: :no_entry:"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}