name: 'Entur/Security/Test Actions'
on:
  push:
    branches:
      - main
  pull_request:

jobs:
    # We run grype and syft scan as a way to do integration testing.
    # if format has changed, and location is no longer updated tests will fail.
    run-grype-and-syft-scan:
      runs-on: ubuntu-24.04
      name: "Run grype and syft scan"
      steps:
          - name: "Checkout repository"
            uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.2
            with:
              persist-credentials: false
          - name: Pull and Save Docker Image
            run: |
              docker pull node:26.3.0-alpine3.24
              
              # Save the pulled image to a tar file
              docker save -o test.tar node:26.3.0-alpine3.24
          - name: "Anchore Syft Scan"
            id: syft-scan
            uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # v0
            with:
              format: spdx-json
              image: test.tar
              output-file: test.spdx.json
              artifact-name: test.spdx.json
        
          - name: "Anchore Grype Scan"
            id: anchore-scan
            uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2 # v7
            with: 
              sbom: test.spdx.json
              by-cve: true
              fail-build: false
              severity-cutoff: critical
          - name: "Upload sarif output as artifact"
            uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
            with:
              name: sarif-result
              path: ${{ steps.anchore-scan.outputs.sarif }}
              overwrite: true
          - name: "Upload sbom output as artifact"
            uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
            with:
              name: sbom-result
              path: test.spdx.json
              overwrite: true

    test-serif-location-fix:
      runs-on: ubuntu-24.04
      needs: run-grype-and-syft-scan
      name: ${{ matrix.test.title }}
      strategy:
          matrix:
              test:
                - title: "Assert location is NOT set when sbom file is missing"
                  include-files: ["sarif"]
                  location-set: false
                - title: "Assert location is set when sbom and sarif file provided"
                  include-files: ["sbom", "sarif"]
                  location-set: true
      env: 
        SARIF_FILE: "output"
        SBOM_FILE: "test.spdx.json"
      steps:
          - name: "Checkout repository"
            uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.2
            with:
              persist-credentials: false
          - name: Download sbom
            uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
            with:
              name: sbom-result
          - name: Download sarif
            uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
            with:
              name: sarif-result
          - name: "Run sarif output fix action"
            uses: ./.github/actions/sarif-output-fix
            with:
              sarif_file: ${{ contains(matrix.test.include-files, 'sarif') && env.SARIF_FILE || '' }}
              sbom_file: ${{ contains(matrix.test.include-files, 'sbom') && env.SBOM_FILE  || '' }}
          - name: "Assert sarif fix"
            uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
            env:
              SARIF_FILE: ${{ env.SARIF_FILE }}
              LOCATION_SET: ${{ matrix.test.location-set }}
            with:
              script: |
                const assertSarifFix = require("./.github/scripts/assert-sarif-fix.js");
                assertSarifFix({ core });


    test-dynamic-secrets:
      runs-on: ubuntu-24.04
      name: ${{ matrix.test.title }}
      strategy:
          matrix:
              test:
                - title: "Should export and clear single secret"
                  export-secrets: "DUMMY_SECRET_FOR_TEST"
                - title: "Should export and clear multiple secrets from comma seperated list"
                  export-secrets: "DUMMY_SECRET_FOR_TEST,DUMMY_SECRET_FOR_TEST_2"
      steps:
        - name: "Checkout repository"
          uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.2
          with:
            persist-credentials: false
        - name: "Export build secrets"
          uses: ./.github/actions/dynamic-secrets
          with:
            mode: export
            export-secrets: ${{ matrix.test.export-secrets }}
            secrets: ${{ toJSON(secrets) }}
        - name: "Assert export"
          uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
          env:
            EXPORT_SECRETS: ${{ matrix.test.export-secrets }}
            SECRETS: ${{ toJSON(secrets) }}
          with: 
            script: |
              const assertExportSecret = require("./.github/scripts/assert-export-secrets.js");
              assertExportSecret({ core });
        - name: "Clear build secrets"
          uses: ./.github/actions/dynamic-secrets
          with:
            mode: clear
            export-secrets: ${{ matrix.test.export-secrets }}
        - name: "Assert clear secrets"
          uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
          env:
            EXPORT_SECRETS: ${{ matrix.test.export-secrets }}
          with: 
            script: |
              const assertClearSecret = require("./.github/scripts/assert-clear-secrets.js");
              assertClearSecret({ core });